import object
import subObject

person = object.user("placeHolder Model", {"ram": []}, "irrelevant", "irrelevant", {"name": "person"})
thing0 = object.object("placeHolder Model", {"ram": []}, {"name": "thing0"})
thing1 = object.object("placeHolder Model", {"ram": []}, {"name": "thing0"})
thing2 = object.object("placeHolder Model", {"ram": []}, {"name": "thing0"})

person = subObject.makeEmptyParent(person)
print(person.trd["sub"])
thing0 = subObject.makeParent(thing0, [thing1, thing2])
print(thing0.trd["sub"])
thing1 = subObject.makeChild(thing1, thing0, "0,0,10")
thing2 = subObject.makeChild(thing2, thing0, "0,0,-10")
print(thing1.trd["sub"])
print(thing2.trd["sub"])
person = subObject.setChildren(person, [thing0])
print(person.trd["sub"])
thing1 = subObject.setParent(thing1, thing0, "0,0,5")
print(thing1.trd["sub"])
print(thing0.trd["mov"] + ": thing 1 mov")
thing0 = subObject.removeChild(thing0, 1)
thing2 = subObject.removeParent(thing2)
print(thing0.trd["sub"] + '\n' + thing2.trd["sub"])
thing0 = subObject.addChild(thing0, thing2)
thing2 = subObject.setParent(thing2, thing0, "0,0,3")
print(thing0.trd["sub"] + '\n' + thing2.trd["sub"])
thing0 = subObject.removeChild(thing0, 1)
thing2 = subObject.removeParent(thing2)
thing2 = subObject.removeSub(thing2)
print(thing2.trd)
