# setup
def saveUni(uni, fileName):
    file = open(fileName + ".py", 'w')
    sameBegin = "# AUTO GENERATED CODE\nimport object\ndef load():\n    uni=object.universe("
    variableMiddle = str(uni.tl) + "," + str(uni.scn) + "," + str(uni.obj) + "," + str(uni.cont) + "," + str(
        uni.funct) + "," + str(uni.rule) + "," + str(uni.tag)
    sameEnd = ")\n    return uni\n# END AUTO GENERATED CODE\n# TO USE: IMPORT THIS FILE AND RUN " + fileName + ".load()"
    file.write(sameBegin + variableMiddle + sameEnd)


def saveScn(scn, fileName):
    objs = []
    for i in scn.obj:
        objs.append("sysh.object.object(" + str(i.mod) + ", " + str(i.trd) + ", " + str(i.tag) + ")")
    file = open(fileName + ".py", 'w')
    sameBegin = "# AUTO GENERATED CODE\nimport object\ndef load():\n    uni=object.universe("
    variableMiddle = str(scn.scp) + "," + str(objs) + "," + str(scn.loc) + "," + str(scn.tag)
    sameEnd = ")\n    return uni\n# END AUTO GENERATED CODE\n# TO USE IMPORT THIS FILE AND RUN " + fileName + ".load()"
    file.write(sameBegin + variableMiddle + sameEnd)

# def saveScnExec(scn, fileName):
#    file = open(fileName+".py", 'w')
#    scnObjs = []
#    objs = ""
#    objReturn = ""
#    objPrintState = ""
#    for i in scn.obj:
#        scnObjs.append("sysh.object.object(" + str(i.mod) + ", " + str(i.trd) + ", " + str(i.tag) + ")")
#    scnBuff = ""
#    for i in scnObjs:
#        if scnObjs.index(i) == 0:
#            scnBuff += ("["+i+", ")
#        elif scnObjs.index(i) == -1:
#            scnBuff += (i + "]")
#        else:
#            scnBuff += (i + ", ")
#    scnObjs = scnBuff
#    for i in scn.obj:
#         objs += ("    " +str(i.tag["name"])+"= sysh.object.object(" + str(i.mod)+", "+str(i.trd)+", "+str(i.tag)+")\n")
#         if scn.obj.index(i) == 0:
#             objReturn += ("    return " + str(i.tag["name"]) + ", ")
#         else:
#             objReturn += (str(i.name) + ", ")
#         objPrintState += ("    print(" + i.tag["name"]+".mod, "+i.tag["name"]+".trd, "+i.tag["name"]+".tag" + ")\n")
#    script = ""
#    for i in scn.scp:
#         if scn.scp.index(i) == 0:
#             continue
#         else:
#             script += ("    " + i + "\n")
#    file.write("# AUTGENERATED CODE\nimport object\ndef load():\n    uni=object.scene("+str(scn.scp)+","+scnObjs+","+str(scn.loc)+","+str(scn.tag)+")\n    return uni:\ndef run():\n    print('obj')\n" + objs + "    print('inital state')\n" + objPrintState + "    print('run script')\n" + script + "    print('final')\n" + objPrintState + objReturn + "\n# END AUTOGENERATED CODE\n# TO USE IMPORT THIS FILE AND RUN "+fileName+".load()")"""


# runtime
if __name__ == "__main__":
    print("Save uni v10.0")
